---
title: "One small change in transportation, one giant leap for the environment"
author: "The (Green)Power Rangers: Ruei-Hung Chen, Andrew Chew, Zhenyu Xuan, Elif Yurek"
date: "16/04/2021"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Note to user: Please ensure that the following packages have been installed prior to running the code.
# Packages can be installed using the command "install.packages('name_of_package')".
# Packages used.
library(dplyr)
library(forcats)
library(ggplot2)
library(ggthemes)
library(highcharter)
library(readxl)
library(scales)
library(shiny)
library(shinythemes)
library(scales)
library(tidyr)

# Empty Shiny App template. 
# ui <- fluidPage("")
# server <- function(input, output) {}
# shinyApp(ui = ui, server = server)
```

<!-- Part 1 -->
## Climate Change & CO^2^ 101
<!-- <<<<<<< HEAD -->

```{r}
data <- read_excel("Data/global emission.3.xlsx") 
df <- data.frame( 
  x= data$`Sub-sector`,
  y=data$`Share of global greenhouse gas emissions (%)`) 
#df 

df_transport <- df %>% slice(1:5)
#df_transport

# Set highcharter options 
options(highcharter.theme = hc_theme_smpl(tooltip = list(valueDecimals = 2))) 

highchart () %>% 
  hc_add_series(
    df, 
    "pie",
    hcaes(
      x = x,
      y = y,
      ),
    name = "CO2 emissions by %"
    )  %>%
  hc_plotOptions(
    series = list(
      showInLegend = FALSE,
      pointFormat = "{point.y}%",
      colorByPoint = TRUE
      )) %>%
  hc_title(
    text = "Total Global CO2 Emissions by Sector in 2016"
    ) 

```







=======

<!-- Part 2 -->
## Unsustainable CO^2^ Emissions
```{r part2 setup, include=FALSE}
# Data for emissions.
p2_emissions_data <- read.csv("Data/owid-co2-data.csv")
p2_emissions_clean <- p2_emissions_data[c("country", "year", "co2", "cumulative_co2", "gas_co2", "cumulative_gas_co2")]

# Data for production.
p2_production_data <- read_excel("Data/production.xlsx")
p2_production_clean <- p2_production_data %>%
  pivot_longer(-c(year), names_to = "Type", values_to = "count") %>% 
  mutate(Type = fct_relevel(Type, "Total Vehicle", after = 2)) %>% 
  group_by(Type) %>%
  filter(year < 2020)

part2_widget = function(emissions_data, production_data) {
  
  shinyApp(
    ui = fluidPage(
      theme = shinytheme("cosmo"),
      
      fluidRow(
        # Plot output for emissions.
        column(6, plotOutput("emissions")),
        
        # Plot output for production.
        column(6, plotOutput("production"))
      ),
      
      fluidRow(
        # Type selector for emissions.
        column(3, radioButtons(
          inputId = "type",
          label = "Type:",
          choices = list("Total" = "Total", "Gas" = "Gas"),
          selected = "Total",
          inline = TRUE)),
        
        # View selector for emissions.
        column(3, radioButtons(
          inputId = "view",
          label = "View:",
          choices = list("Annual" = "Annual", "Cumulative" = "Cumulative"),
          selected = "Annual",
          inline = TRUE)),
        
        # View selector for production.
        column(6, radioButtons(
          inputId = "vehicle_type",
          label = "Type:",
          choices = list("Total" = 1, "Commercial" = 2, "Personal Vehicle"= 3),
          selected = 1,
          inline = TRUE))
      ),
      
      fluidRow(
        # Show both for comparison selector for emissions.
        column(3, checkboxInput(
          inputId = "showBoth",
          label = "Show Both (For Comparison)",
          value = TRUE
        )),
        
        # Country selector for emissions.
        column(3, selectInput(
          inputId = "country",
          label = "Country:",
          choices = unique(emissions_data$country),
          selected = "World")),
        
        column(6, )
      ),
      
      # Year range slider widget.
      fluidRow(
        column(6, sliderInput(
          inputId = "years",
          label = "Year Range:",
          # Even though data since 1751 was provided, show data starting from 1900s.
          min = 1900,
          max = 2019,
          value = c(2000, 2019),
          step = 1,
          width = "100%",
          sep = "",
          dragRange = TRUE)),
        column(6, ))
    ),

    server = function(input, output, session) {
      
      # Emissions.
      # Put together dataset based on user selections.
      selected_emissions_data <- reactive({
        # Annual.
        if (input$view == "Annual") {
          emissions_data %>%
            filter(country == input$country) %>%
            group_by(year) %>%
            filter(year >= input$years[1] & year <= input$years[2]) %>%
            summarise(Total = sum(co2, na.rm = TRUE),
                      Gas = sum(gas_co2, na.rm = TRUE))
        }
        
        # Cumulative.
        else {
          emissions_data %>%
            filter(country == input$country) %>%
            group_by(year) %>%
            filter(year >= input$years[1] & year <= input$years[2]) %>%
            summarise(Total = sum(cumulative_co2, na.rm = TRUE),
                      Gas = sum(cumulative_gas_co2, na.rm = TRUE))
        }
      })
      
      # Put together plot based on user selections.
      selected_emissions_plot <- reactive({
        if (input$showBoth == TRUE) {
          ggplot(selected_emissions_data(), aes(x = year)) +
            geom_point(aes(y = Total, colour = "Total")) +
            geom_point(aes(y = Gas, colour = "Gas")) +
            geom_path(aes(y = Total, colour = "Total")) +
            geom_path(aes(y = Gas, colour = "Gas")) +
            geom_rect(aes(xmin = 2007.5, xmax = 2009.5, ymin = 0, ymax = Inf), alpha = 0.01, fill = "red") +
            geom_text(aes(x = 2008.5, y = max(selected_emissions_data()$Total * 0.45), label = "Financial Crisis"), size = 3) +
            geom_rect(aes(xmin = 2018.5, xmax = 2020, ymin = 0, ymax = Inf), alpha = 0.01, fill = "red") +
            geom_text(aes(x = 2019, y = max(selected_emissions_data()$Total * 0.65), label = "COVID-19"), size = 3) +
            scale_color_manual("",
                               breaks = c("Total", "Gas"),
                               values = c("#d95f02", "#7570b3")) +
            xlim(min(selected_emissions_data()$year), max(selected_emissions_data()$year) + 1) +
            labs(title = paste(input$view, "Carbon Dioxide Emissions"),
                 x = "Year",
                 y = expression(paste("CO"^"2", " Emissions (million tonnes)")),
                 caption = "Data source: https://github.com/owid/co2-data") +
            theme_wsj() + 
            theme(plot.title = element_text(size = rel(0.65), hjust = 0.5),
                  plot.caption = element_text(size = rel(0.35)),
                  axis.title = element_text(size = rel(0.5)),
                  legend.position = "top",
                  legend.justification = "center")
        }
        else {
          ggplot(selected_emissions_data(), aes(x = year)) +
            geom_point(aes_string(y = input$type)) +
            geom_path(aes_string(y = input$type)) +
            geom_rect(aes(xmin = 2007.5, xmax = 2009.5, ymin = min(selected_emissions_data()[[input$type]]) * 0.95, ymax = Inf), alpha = 0.01, fill = "red") +
            geom_text(aes(x = 2008.5, y = min(selected_emissions_data()[[input$type]] * 1.05), label = "Financial Crisis"), size = 3) +
            geom_rect(aes(xmin = 2018.5, xmax = 2020, ymin = min(selected_emissions_data()[[input$type]]) * 0.95, ymax = Inf), alpha = 0.01, fill = "red") +
            geom_text(aes(x = 2019, y = min(selected_emissions_data()[[input$type]] * 1.15), label = "COVID-19"), size = 3) +
            xlim(min(selected_emissions_data()$year), max(selected_emissions_data()$year) + 1) +
            ylim(min(selected_emissions_data()[[input$type]]) * 0.95, max(selected_emissions_data()[[input$type]]) * 1.05) +
            labs(title = paste(input$view, "Carbon Dioxide Emissions"),
                 subtitle = paste(input$type),
                 x = "Year",
                 y = expression(paste("CO"^"2", " Emissions (million tonnes)")),
                 caption = "Data source: https://github.com/owid/co2-data") +
            theme_wsj() +
            theme(plot.title = element_text(size = rel(0.65), hjust = 0.5),
                  plot.subtitle = element_text(size = rel(0.5), hjust = 0.5),
                  plot.caption = element_text(size = rel(0.35)),
                  axis.title = element_text(size = rel(0.5)))
        }
      })

      # Emissions plot.
      output$emissions <- renderPlot({selected_emissions_plot()})
      
      # Production
      # Put together dataset based on user selections.
      selected_production_data <- reactive({
        if (input$vehicle_type == 1){
          production_data %>% 
            filter(Type == "Total Vehicle") %>%
            mutate(count = count/1000000)
        } else if (input$vehicle_type == 2){
          production_data %>% 
            filter(Type != "Cars") %>%
            mutate(count = count/1000000)
        } else {
          production_data %>% 
            filter(Type != "Commercial") %>%
            mutate(count = count/1000000) 
        }
      })
    
      # Production plot.
      output$production <- renderPlot({
        selected_production_data() %>% 
          ggplot(aes(x = year, y = count, colour = Type)) +
          scale_color_manual(values = c("#d95f02", "#7570b3")) +
          geom_line(lwd = 1) +
          geom_rect(aes(xmin = 2007.5, xmax = 2009.5, ymin = min(selected_emissions_data()[[input$type]]) * 0.95, ymax = Inf), alpha = 0.01, fill = "red") +
          geom_text(aes(x = 2008.5, y = min(selected_emissions_data()[[input$type]] * 1.05), label = "Financial Crisis"), size = 3) +
          geom_rect(aes(xmin = 2018.5, xmax = 2020, ymin = min(selected_emissions_data()[[input$type]]) * 0.95, ymax = Inf), alpha = 0.01, fill = "red") +
          geom_text(aes(x = 2019, y = min(selected_emissions_data()[[input$type]] * 1.15), label = "COVID-19"), size = 3) +
          xlim(2000, 2020) +
          ylim(min(selected_production_data()$count * 0.95), max(selected_production_data()$count * 1.05)) +
          labs(title = "Annual Vehicle Production",
                 subtitle = paste(input$vehicle_type),
                 x = "Year",
                 y = "Vehicles Produced (millions)",
                 caption = "Data source: https://www.oica.net/category/production-statistics/") +
          theme_wsj() +
          theme(plot.title = element_text(size = rel(0.65), hjust = 0.5),
                plot.subtitle = element_text(size = rel(0.5), hjust = 0.5),
                plot.caption = element_text(size = rel(0.35)),
                axis.title = element_text(size = rel(0.5)))
          })
    },

    options = list(height = 500)
  )
}
```

```{r part2, echo=FALSE}
# Run the widget for part 2.
part2_widget(p2_emissions_clean, p2_production_clean)
```

<!-- Part 3 -->
## What's your "Contribution"?

```{r}
ui <- fluidPage(
  
  sliderInput("distance", "How far do you travel every day on average? (km)",min = 0, max = 1000, value = 500),
  plotOutput("distPlot"),
  checkboxGroupInput("icons", "What type of primary vehicle do you use?",
                     choiceNames = list(icon("car"), icon("train"),
                                        icon("plane"),icon("motorcycle"),icon("bus"),icon("subway"), icon("bicycle")),
                     choiceValues = list("car with CO2 emission 10 per kilometer", "train with CO2 emission 8 per kilometer", "plane with CO2 emission 7 per kilometer","motorcycle with CO2 emission 6 per kilometer","bus with CO2 emission 5 per kilometer","subway with CO2 emission 3 per kilometer", "bicycle with CO2 emission 1 per kilometer")
  ),
  textOutput("txt")
)

server <- function(input, output, session) {
  output$txt <- renderText({
    icons <- paste(input$icons, collapse = ", ")
    paste("You chose", icons)
    })
  # Reactive expression to create data frame of all input values ----
}

shinyApp(ui, server)
```

```{r}
#the CO2 emission per kilometer for various types of cars
car_index <- 10
train_index <- 8
flight_index <- 7
motorcycle_index <- 6
bus_index <- 5
subway_index <- 3
bike_index <- 1

#calculate the CO2 emission for each vehicle
time = c(2021,2022,2023,2024,2025)
CO2_emission_car <- car_index*(time - 2021)
CO2_emission_train <- train_index*(time - 2021)
CO2_emission_flight <- flight_index*(time - 2021)
CO2_emission_motorcycle <- motorcycle_index*(time - 2021)
CO2_emission_bus <- bus_index*(time - 2021)
CO2_emission_subway <- subway_index*(time - 2021)
CO2_emission_bike <- bike_index*(time - 2021)

#plot the graph
plot(CO2_emission_car,type = "o",col = "red", xlab = "Time (years)", ylab = "CO2 emission", 
   main = "Impact of choosing alternative means of transports",lwd=3)
lines(CO2_emission_train, type = "o", col = "orange",lwd=3)
lines(CO2_emission_flight, type = "o", col = "blue",lwd=3)
lines(CO2_emission_motorcycle, type = "o", col = "yellow",lwd=3)
lines(CO2_emission_bus, type = "o", col = "grey",lwd=3)
lines(CO2_emission_subway, type = "o", col = "black",lwd=3)
lines(CO2_emission_bike, type = "o", col = "green",lwd=3)

legend("topleft", legend = c("car","train","flight","motorcycle","bus","subway","bike"),col=c("red","orange","blue","yellow","grey","black", "green"), lwd = 2, cex = 0.7)
```

<!-- Part 4 -->
## How can you help?

<!-- Conclusion -->
## Flatten the curve!
